### ISSUE TITLE
X-Frame-Options seem to block import

### ISSUE THREAD

**Issue by davidnuescheler** [kptdobe/helix-webui-importer#17]
```
Refused to display 'https://www.astrazeneca.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
ui.js:180 Imported: 1 => https://www.astrazeneca.com/our-company/leadership/marc-dunoyer.html
```

**Comment by davidnuescheler** [comment]
i think this because of a redirect... to https://www.astrazeneca.com/our-company/leadership.html

**Comment by kptdobe** [comment]
With `hlx import`, no x-frame-options error. Only console log: `Cannot transform http://localhost:3001/our-company/leadership/marc-dunoyer.html?host=https%3A%2F%2Fwww.astrazeneca.com - redirected to http://localhost:3001/our-company/leadership.html`
